---
language: node_js
node_js:
  - "node"
cache: yarn
addons:
  apt:
    packages:
      - expect
install:
  - yarn global add @vue/cli @vue/cli-init
script:
  - ./vue-cli-install-test.exp
  - cd test
  - yarn install
  - yarn build
